// AUTOMATISCH aus "Business Case Copilot.dc.html" extrahiert – Texte wortgleich zur
// Designvorlage. Platzhalter im {{ name }}-Format werden zur Laufzeit ersetzt.
// Bei Änderungen an der Vorlage neu erzeugen, nicht von Hand editieren.

export type DeckSlideContent = {
  nr: number;
  label: string;
  /** Hintergrundfarbe der Folie laut Vorlage (Navy oder Paper). */
  bg: string;
  notes: string;
  eyebrow: string | null;
  title: string | null;
  /** true = Fußzeile enthält zusätzlich den Kalkulationshinweis (die acht Rechenfolien). */
  disclaimer: boolean;
  /** Alle weiteren Textbausteine in Reihenfolge der Vorlage. */
  items: string[];
};

export const DECK_FOOTER_LEFT = "Business Case Microsoft 365 Copilot";
export const DECK_FOOTER_DISCLAIMER = "Näherungswerte zur Grobkalkulation · Details klären wir im Gespräch";

export const DECK_SLIDES: DeckSlideContent[] = [
  {
    nr: 1,
    label: "Titel",
    bg: "#0A2E5C",
    notes: "Entscheidungsvorlage, keine Produktpräsentation. Die Zahlen stammen aus dem beigefügten ROI-Rechner.",
    eyebrow: null,
    title: "copilotenschule.de",
    disclaimer: false,
    items: [
      "§ 00 — Entscheidungsvorlage",
      "Business Case",
      "Microsoft 365 Copilot",
      "Grundlage für die Entscheidung über Einführung, Qualifizierung und Investition.",
      "Die vollständige Berechnung liegt nachvollziehbar in einer eigenen Excel-Datei vor, die ebenfalls zum Download bereitsteht.",
      "Unternehmen",
      "{{ firma }}",
      "Stand",
      "{{ datum }}",
      "Ansprechpartner",
      "{{ ansprechpartner }}",
    ],
  },
  {
    nr: 2,
    label: "Executive Summary",
    bg: "#F3F5F8",
    notes: "Die vier Kennzahlen kommen direkt aus dem ROI-Rechner. Alles Weitere begründet sie.",
    eyebrow: "§ 01 — Executive Summary",
    title: "Executive Summary",
    disclaimer: true,
    items: [
      "Planungsrechnung für {{ firma }}: {{ nutzerText }} geplante Nutzer, Betrachtung über 36 Monate, {{ szenarioText }} Szenario.",
      "ROI Jahr 1",
      "{{ roiY1 }}",
      "Break-even",
      "{{ breakEven }}",
      "Investition Jahr 1",
      "{{ costY1 }}",
      "Netto-Nutzen 3 Jahre",
      "{{ net3 }}",
      "Herleitung",
      "Nutzer × Zeitersparnis × Vollkosten-Stundensatz × 50 % Realisierung, monatlich über 36 Monate — gegengerechnet mit Lizenzen, Training, IT-Setup und Change.",
      "Annahmen",
      "8 Std. Zielwert je Person und Monat über eine Anlaufkurve ab 60 %. Kein agentisches Zusatzpotenzial eingerechnet.",
      "Quellen",
      "Forrester TEI Microsoft 365 Copilot (2025), plausibilisiert an DWP- und UK-Cross-Government-Auswertungen.",
    ],
  },
  {
    nr: 3,
    label: "Warum jetzt",
    bg: "#F3F5F8",
    notes: "Kein Drohszenario. Der Punkt ist die Zeitachse des Kompetenzaufbaus.",
    eyebrow: "§ 02 — Zeitpunkt",
    title: "Warum jetzt handeln",
    disclaimer: false,
    items: [
      "KI-unterstützte Arbeit ist kein Werkzeugwechsel, sondern eine Lernreise — von der ersten Frage an ein Sprachmodell bis zu Abläufen, die Agenten übernehmen.",
      "01",
      "Die erste Frage",
      "Ein Text, eine Zusammenfassung, ein Versuch. Der Moment, in dem das Werkzeug greifbar wird.",
      "02",
      "Der tägliche Chat",
      "Regelmäßige Nutzung, eigene Prompts, ein Gefühl dafür, was trägt und was nicht.",
      "03",
      "Eigene Agenten",
      "Wiederkehrende Abläufe werden beschrieben, geprüft und an einen Agenten übergeben.",
      "04",
      "Agentische Arbeit",
      "Menschen steuern und prüfen, Systeme führen aus. Die Arbeitsteilung verschiebt sich.",
      "Der Weg zu sicherer und effizienter KI-unterstützter Büroarbeit ist eine Treppe. Die Stufen lassen sich nicht überspringen.",
      "Wer erst startet, wenn Agenten Standard sind, beginnt trotzdem bei Stufe eins — nur mit weniger Zeit und unter höherem Druck.",
    ],
  },
  {
    nr: 4,
    label: "Agenten",
    bg: "#F3F5F8",
    notes: "Agenten sind die nächste Stufe, nicht der Einstieg. Sie setzen dokumentierte Prozesse und geübte Nutzer voraus.",
    eyebrow: "§ 03 — Ausblick",
    title: "Die nächste Stufe: Agenten",
    disclaimer: false,
    items: [
      "Agenten bauen auf Erfahrung auf. Wer heute keine Anwendungsfälle beschreiben kann, kann morgen keine automatisieren.",
      "Mit Erfahrung",
      "01",
      "Copilot als Assistenz",
      "↓",
      "02",
      "Routine im Arbeitsalltag",
      "↓",
      "03",
      "Kompetenz und eigene Use Cases",
      "↓",
      "04",
      "Agenten und Automatisierung",
      "Ohne Erfahrung",
      "Agenten übernehmen Abläufe, die vorher jemand verstanden, geübt und beschrieben hat. Fehlt diese Vorarbeit, bleiben sie eine Demo im Pilotprojekt.",
      "Der Kompetenzaufbau ist damit keine Vorstufe der Automatisierung, sondern ihre Voraussetzung.",
    ],
  },
  {
    nr: 5,
    label: "Zwei Tracks",
    bg: "#F3F5F8",
    notes: "Kernbotschaft: Der Kompetenzaufbau ist nicht an die kostenpflichtige Lizenz gebunden.",
    eyebrow: "§ 04 — Einstieg",
    title: "Der Einstieg in zwei Tracks",
    disclaimer: false,
    items: [
      "Kompetenzaufbau kann sofort beginnen. Nicht alle Mitarbeitenden benötigen dafür eine Zusatzlizenz.",
      "Track 1",
      "Copilot Chat",
      "In Microsoft 365 enthalten. Breite Befähigung zu KI-unterstützter Arbeit, spürbare Reduktion von Schatten-KI.",
      "Geeignet für die gesamte Belegschaft.",
      "Track 2",
      "Microsoft 365 Copilot",
      "Lizenzpflichtig. Tiefe Nutzung in Word, Excel, Outlook und Teams, Automatisierung und Agenten.",
      "Geeignet für Rollen mit hoher Dokumenten- und Abstimmungslast.",
    ],
  },
  {
    nr: 6,
    label: "Vier Gründe",
    bg: "#F3F5F8",
    notes: "Bewusst gleichgewichtig. Effizienz ist nur einer von vier Gründen.",
    eyebrow: "§ 05 — Motive",
    title: "Warum Unternehmen Copilot einführen",
    disclaimer: false,
    items: [
      "01",
      "Effizienz",
      "Routinearbeiten in Minuten statt Stunden.",
      "02",
      "Entlastung",
      "Weniger Arbeit, die niemand gern macht.",
      "03",
      "Qualität",
      "Bessere Vorbereitung, vollständigere Unterlagen.",
      "04",
      "Neue Möglichkeiten",
      "Aufgaben, die vorher am Aufwand gescheitert sind.",
      "Wer KI ausschließlich als Effizienzprojekt versteht, nutzt nur einen kleinen Teil des Potenzials.",
      "Beispiel: eine individuelle Präsentation für jede einzelne Kundenanfrage bereitstellen, basierend auf einer umfangreichen Excel-Berechnung, die ebenfalls bereitgestellt wird — beides erzeugt aus den Angaben des Interessenten. Nicht leistbar? QED!",
    ],
  },
  {
    nr: 7,
    label: "Was Unternehmen gewinnen",
    bg: "#0A2E5C",
    notes: "Die Wirkungen, die sich schlecht in Euro fassen lassen, aber im Haus zuerst auffallen.",
    eyebrow: "§ 06 — Wirkung",
    title: "Weniger Frust",
    disclaimer: false,
    items: [
      "Liegengebliebene Kleinarbeit staut sich nicht mehr auf. Qualitätssicherung durch dedizierte Prüf-Prozesse.",
      "Employer Branding",
      "Attraktive Arbeitsbedingungen und moderne Werkzeuge sind ein Argument im Recruiting.",
      "Schnellere Einarbeitung",
      "Neue Kolleginnen und Kollegen finden Wissen selbst. Riesige Zeitersparnis auch für die einarbeitenden Kolleginnen und Kollegen.",
      "Bessere Zusammenarbeit",
      "Protokolle, Zusammenfassungen und Stände sind stets verfügbar. Bessere Vorbereitung der Meetings.",
      "Neue Angebote",
      "Prozesse und Produkte, die vorher aus Ressourcenmangel nicht realisierbar waren werden möglich.",
      "Mehr Innovationskraft",
      "Ideen verproben. Prototypen in Stunden statt Wochen - selbst erstellt durch die Fachkräfte. Abgesichert durch Genehmigungs-Prozesse.",
    ],
  },
  {
    nr: 8,
    label: "Risiken des Abwartens",
    bg: "#F3F5F8",
    notes: "Sachlich halten. Jedem Risiko steht eine konkrete Gegenmaßnahme gegenüber.",
    eyebrow: "§ 07 — Risiken",
    title: "Risiken des Abwartens",
    disclaimer: false,
    items: [
      "Risiko",
      "Gegenmaßnahme",
      "Der Rückstand zum Innovations- und Price-Leader wächst",
      "Mit Copilot Chat lizenzfrei starten und die Lernkurve vorziehen.",
      "Schatten-KI wächst. Risiken im Datenschutz und in der IP-Absicherung ernst nehmen.",
      "Freigegebenes Werkzeug, klare Regeln, Schulung statt Verbot.",
      "Agenten und Automatisierungen werden, wenn überhaupt, von Spezialkräften gebaut — sofern Budget verfügbar ist",
      "Use Cases aus dem Alltag dokumentieren, bevor durch den User selbst streckenweise automatisiert wird.",
      "Die größte Veränderung seit Einführung der EDV wird verschlafen",
      "Mit einer begrenzten Gruppe beginnen und messbar ausrollen.",
    ],
  },
  {
    nr: 9,
    label: "ROI",
    bg: "#F3F5F8",
    notes: "Ab hier die Rechnung. Alle Werte stammen aus dem ROI-Rechner, der dem Business Case beiliegt.",
    eyebrow: "§ 08 — Rechnung",
    title: "Return on Investment",
    disclaimer: true,
    items: [
      "Realisierter Nutzen abzüglich Gesamtkosten, geteilt durch die Gesamtkosten. Ein ROI von 0 % ist der Break-even.",
      "Realisierter Nutzen Jahr 1",
      "{{ benefitY1 }}",
      "Gesamtkosten Jahr 1",
      "{{ costY1 }}",
      "Realisierter Nutzen 3 Jahre",
      "{{ benefit3 }}",
      "Gesamtkosten 3 Jahre",
      "{{ cost3 }}",
      "Netto-Nutzen 3 Jahre",
      "{{ net3 }}",
      "ROI Jahr 1",
      "{{ roiY1 }}",
      "ROI 3 Jahre",
      "{{ roi3 }}",
      "{{ roiHinweis }}",
    ],
  },
  {
    nr: 10,
    label: "Investition",
    bg: "#F3F5F8",
    notes: "Vier Kostenblöcke. Über drei Jahre wird die Lizenz typischerweise der größte Posten.",
    eyebrow: "§ 09 — Kosten",
    title: "Investition über drei Jahre",
    disclaimer: true,
    items: [
      "Gesamtkosten Jahr 1: {{ costY1 }} · Gesamtkosten über 36 Monate: {{ cost3 }}",
      "Lizenzen",
      "{{ blockLic }}",
      "{{ blockLicPct }} der Gesamtkosten",
      "Training",
      "{{ blockTrain }}",
      "{{ blockTrainPct }} der Gesamtkosten",
      "IT-Setup",
      "{{ blockIt }}",
      "{{ blockItPct }} der Gesamtkosten",
      "Change & Adoption",
      "{{ blockChange }}",
      "{{ blockChangePct }} der Gesamtkosten",
      "Training läuft im ersten Jahr vollständig, in Jahr 2 und 3 mit jeweils 50 % des Budgets als fortlaufende Weiterbildung. IT-Setup fällt einmalig an.",
      "Change und Adoption sind mit 12 % der jährlichen Lizenz-, Trainings- und IT-Kosten angesetzt.",
    ],
  },
  {
    nr: 11,
    label: "Zeitersparnis",
    bg: "#F3F5F8",
    notes: "Der Realisierungsfaktor von 50 Prozent ist die wichtigste Vorsichtsannahme der Rechnung.",
    eyebrow: "§ 10 — Nutzenlogik",
    title: "Wie aus Zeitersparnis Nutzen wird",
    disclaimer: true,
    items: [
      "Nutzer",
      "{{ nutzerText }}",
      "×",
      "Ø Zeitersparnis / Monat",
      "{{ hoursY1 }}",
      "×",
      "Stundensatz",
      "{{ rateText }}",
      "×",
      "Realisierung",
      "50 %",
      "Ergebnis je Nutzer und Jahr",
      "{{ benefitPerUser }}",
      "Im ersten Jahr werden durchschnittlich {{ hoursY1 }} brutto je Person und Monat angesetzt — nach einem Startniveau von 60 % direkt nach dem Kick-off.",
      "Die Rechnung unterstellt nicht, dass jede gesparte Stunde als Personalkostensenkung realisiert wird. Angesetzt ist — sehr konservativ — die Hälfte.",
      "Nicht eingerechnet: leistungsfähigere Modelle, neue Werkzeuge, tiefere Prozessintegration und agentische Abläufe.",
    ],
  },
  {
    nr: 12,
    label: "Szenarien",
    bg: "#F3F5F8",
    notes: "Die Szenarien unterscheiden sich nicht durch eine Adoptionsquote, sondern durch die angesetzte Zeitersparnis.",
    eyebrow: "§ 11 — Szenarien",
    title: "Zwei plausible Szenarien",
    disclaimer: true,
    items: [
      "Kennzahl",
      "Realistisch",
      "Forrester TEI",
      "Ziel-Zeitersparnis je Person",
      "8 Std./Monat",
      "9 Std./Monat",
      "Wirtschaftlich realisierbar",
      "50 %",
      "50 %",
      "Realisierter Nutzen Jahr 1",
      "{{ realBenefitY1 }}",
      "{{ studyBenefitY1 }}",
      "ROI Jahr 1",
      "{{ realRoiY1 }}",
      "{{ studyRoiY1 }}",
      "ROI 3 Jahre",
      "{{ realRoi3 }}",
      "{{ studyRoi3 }}",
      "Für alle geschulten Personen wird eine durchschnittliche Zeitersparnis angesetzt — keine künstliche Adoptionsquote. Grundlage sind die Forrester-Werte.",
    ],
  },
  {
    nr: 13,
    label: "Break-even",
    bg: "#F3F5F8",
    notes: "Kumulierter Nutzen gegen kumulierte Kosten über 36 Monate. Der Schnittpunkt ist der Break-even.",
    eyebrow: "§ 12 — Verlauf",
    title: "Wirtschaftliche Entwicklung über 36 Monate",
    disclaimer: true,
    items: [
      "Break-even im {{ szenarioTextLower }} Szenario: {{ breakEven }}.",
      "KUMULIERTER NUTZEN",
      "KUMULIERTE KOSTEN",
      "BREAK-EVEN {{ breakEvenShort }}",
      "SKALA BIS {{ chartMaxLabel }}",
      "[SVG-DIAGRAMM]",
    ],
  },
  {
    nr: 14,
    label: "Adoption",
    bg: "#F3F5F8",
    notes: "Übergang von der Rechnung zur Umsetzung. Der Nutzen entsteht erst durch veränderte Arbeitsweise.",
    eyebrow: "§ 13 — Umsetzung",
    title: "Adoption als Erfolgsfaktor",
    disclaimer: false,
    items: [
      "Copilot einzuführen bedeutet, Arbeitsweisen zu verändern. Die Lizenz ist der erste Schritt einer Kette, nicht ihr Ergebnis.",
      "01",
      "Lizenz",
      "→",
      "02",
      "Training",
      "→",
      "03",
      "Übung",
      "→",
      "04",
      "Community",
      "→",
      "05",
      "Gewohnheiten",
      "Technologie",
      "Lizenzen, Berechtigungen, Datenqualität, Governance.",
      "Kompetenz",
      "Prompting, Kontext, Qualitätsprüfung, App-Wissen.",
      "Verhalten",
      "Neue Routinen, geteilte Beispiele, veränderte Abläufe.",
    ],
  },
  {
    nr: 15,
    label: "Lernreise",
    bg: "#0A2E5C",
    notes: "Die Lernreise ist das Standardformat: Kick-off plus vier Online-Sessions je Gruppe.",
    eyebrow: "§ 14 — Programm",
    title: "Unsere Lernreise",
    disclaimer: false,
    items: [
      "Ein durchgehender Weg von der ersten Stunde bis zur eigenständigen Nutzung im Team.",
      "01",
      "Kick-off",
      "4 Stunden, vor Ort oder online. Darin: Features und Workflows des Copilot Chat, Advanced Prompting, sichere und gesetzeskonforme Nutzung von KI inklusive EU-AI-Act-Zertifikat, Qualitätssicherung mit KI, Use Cases beschreiben und umsetzen",
      "02",
      "Lernreise",
      "Vier Online-Sessions pro Gruppe à 2 Stunden. Darin Copilot-Features und Nutzung in ein bis zwei Office-Apps, inklusive Übungen und eigenen kleinen Use Cases",
      "03",
      "Praxis",
      "Fallstudien und eigene Use Cases werden zwischen den Online-Sessions in den verschiedenen Apps ausprobiert",
      "04",
      "Community",
      "Gemeinsamer Aufbau Ihrer Community in SharePoint oder als Teams-Gruppe. Befüllung mit Content und Betreuung auf Zeit durch uns (auf Wunsch)",
      "05",
      "Weiterentwicklung",
      "Unterlagen sowie Online- und Präsenz-Weiterbildungen parallel zum technologischen Fortschritt. Vertiefung der KI-Unterstützung, etwa im Aufbaukurs „Agenten, Studio und Power Automate\" oder fachspezifisch mit „Copilot im Vertrieb\"",
    ],
  },
  {
    nr: 16,
    label: "Bausteine",
    bg: "#F3F5F8",
    notes: "Beispielpreise, keine Angebotspreise. Der konkrete Zuschnitt hängt von Gruppengrößen und Standorten ab.",
    eyebrow: "§ 15 — Bausteine",
    title: "Wir helfen, den Change zu starten und zu sichern",
    disclaimer: true,
    items: [
      "{{ preisHinweis }}",
      "Kick-off Workshop",
      "4 Stunden je Gruppe, vor Ort oder online",
      "{{ preisKickoff }}",
      "Lernreise-Session",
      "2 Stunden online, vier Termine je Gruppe",
      "{{ preisLernreise }}",
      "Keynote",
      "Impuls für Townhall oder Führungskräftetag",
      "{{ preisKeynote }}",
      "Launch Day",
      "Info- und Demo-Stand bei Ihnen vor Ort, mit Berater am Stand",
      "{{ preisLaunch }}",
      "Betriebsrat-Workshop",
      "1 Tag inklusive Erstellung der Unterlagen",
      "{{ preisBr }}",
      "Führungskräfte",
      "Halber Tag: Erwartungen, Vorbild, Steuerung",
      "auf Anfrage",
      "Admin-Workshop",
      "Halber Tag: Konfiguration und Berechtigungen",
      "auf Anfrage",
      "Train-the-Trainer",
      "Ausbildung interner Champions und Multiplikatoren",
      "auf Anfrage",
    ],
  },
  {
    nr: 17,
    label: "Warum Copilotenschule",
    bg: "#F3F5F8",
    notes: "Kurz halten. Spezialisierung, Erfahrung, Praxisnähe.",
    eyebrow: "§ 16 — Anbieter",
    title: "Warum Copilotenschule",
    disclaimer: false,
    items: [
      "Wir machen nur eines: Microsoft Copilot. Praktische Umsetzung mit Ihren Werkzeugen und in Ihrer Arbeitsrealität.",
      "2011",
      "Yellow-Boat Consulting, Köln. Über 15 Jahre Training und Digitalisierung.",
      "2.000+",
      "geschulte Wissensarbeiter, Fach- und Führungskräfte.",
      "100 %",
      "Fokus auf Microsoft Copilot. Keine Tool-Demos, keine Videokurse.",
      "DACH",
      "Live vor Ort, online oder in der Akademie in Köln. DSGVO-konform.",
      "„Ich will, dass die Leute Fähigkeiten mitnehmen, die sie sofort umsetzen können.\"",
      "Dirk Schöbel · General Manager, Marriott Hotel",
    ],
  },
  {
    nr: 18,
    label: "Referenzen",
    bg: "#F3F5F8",
    notes: "Bei Bedarf eine Referenzstory aus der Branche des Kunden ergänzen.",
    eyebrow: "§ 17 — Referenzen",
    title: "Unternehmen, die mit uns trainieren",
    disclaimer: false,
    items: [
      "Konzerne, Mittelstand, öffentliche Hand und Forschung.",
      "REWE",
      "Pernod Ricard",
      "Lekkerland",
      "Marriott Hotels",
      "Med360Grad",
      "IHK Nord Westfalen",
      "Sun Chemicals",
      "Abbott",
      "Atlantic Lloyd",
      "DFKI",
      "Hessisches Familienministerium",
      "Kommunales Bildungswerk",
    ],
  },
  {
    nr: 19,
    label: "Entscheidungsvorlage",
    bg: "#0A2E5C",
    notes: "Die eine Folie, die im Gremium liegen bleibt. Beantragter Umfang, Investition, Nutzen, nächste Schritte.",
    eyebrow: "§ 18 — Entscheidung",
    title: "Entscheidungsvorlage",
    disclaimer: true,
    items: [
      "Beantragt",
      "Umfang",
      "{{ nutzerText }} Nutzer",
      "Investition Jahr 1",
      "{{ costY1 }}",
      "{{ investSplit }}",
      "Erwarteter Nutzen Jahr 1",
      "{{ benefitY1 }}",
      "Erwarteter Break-even",
      "{{ breakEven }}",
      "Empfohlene Gruppen",
      "{{ gruppenText }}",
      "Empfohlene nächste Schritte",
      "01",
      "Zwei bis drei Anwendungsfälle priorisieren und eine Baseline messen.",
      "02",
      "Launch, Kick-off und Lernreise für die ersten Gruppen terminieren, Kick-off innerhalb von sechs Wochen.",
      "03",
      "Betriebsrat und Führungskräfte früh einbinden, vor dem Rollout der ersten Gruppen.",
      "04",
      "Nutzung und Wirkung nach sechs Monaten überprüfen und Annahmen nachschärfen.",
      "Planungsrechnung, kein Wirkungsversprechen. Grundlage sind der beigefügte ROI-Rechner sowie die Forrester-TEI-Studie zu Microsoft 365 Copilot.",
      "copilotenschule.de",
    ],
  },
  {
    nr: 20,
    label: "Gespräch",
    bg: "#F3F5F8",
    notes: "Abschluss: Einladung zum Gespräch, Termin direkt buchbar.",
    eyebrow: "§ 19 — Gespräch",
    title: "copilotenschule.de",
    disclaimer: false,
    items: [
      "Laden Sie mich zu Ihrer Beratung ein",
      "Dann stehe ich gerne Rede und Antwort — zu den Annahmen dieser Rechnung, zum Zuschnitt der Lernreise und zu allem, was im Gremium offen bleibt.",
      "Ihr Ansprechpartner",
      "Martin Lang",
      "Geschäftsführer, Yellow-Boat Consulting",
      "martin@yellow-boat.com",
      "Termin direkt buchen",
      "30 Minuten zuschalten in Ihre Beratung — kostenlos und unverbindlich.",
      "Termin wählen →",
      "Alternativ: +49 221 950 187 74",
      "copilotenschule.de · Eine Marke der Yellow-Boat Consulting",
      "+49 221 950 187 74",
    ],
  },
];
